import { useEffect, useRef } from 'react';

interface Particle {
  x: number;
  y: number;
  baseVx: number;
  baseVy: number;
  vx: number;
  vy: number;
  radius: number;
  baseRadius: number;
  color: string;
  glowColor: string;
  alpha: number;
  targetAlpha: number;
  pulseSpeed: number;
  isHexBokeh: boolean;
  mass: number;
}

interface InteractiveSpark {
  x: number;
  y: number;
  vx: number;
  vy: number;
  radius: number;
  alpha: number;
  decay: number;
  color: string;
}

export function ParticleField() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d', { alpha: true });
    if (!ctx) return;

    let animationFrameId: number;
    let dpr = window.devicePixelRatio || 1;
    let width = 0;
    let height = 0;

    // Mouse state with smooth interpolation
    const mouse = {
      x: -1000,
      y: -1000,
      targetX: -1000,
      targetY: -1000,
      prevX: -1000,
      prevY: -1000,
      speed: 0,
      active: false,
      radius: 180, // influence radius
    };

    const handleResize = () => {
      if (!canvas) return;
      dpr = window.devicePixelRatio || 1;
      width = window.innerWidth;
      height = window.innerHeight;
      canvas.width = width * dpr;
      canvas.height = height * dpr;
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;
      ctx.scale(dpr, dpr);
    };

    handleResize();
    window.addEventListener('resize', handleResize);

    // Color palettes matching the Pioneer Corn visual identity:
    // Glowing golden pollen, rich amber seed dust, emerald leaf tones, and subtle mint bokeh
    const palette = [
      { base: 'rgba(251, 191, 36, ', glow: 'rgba(245, 158, 11, 0.4)' }, // Gold
      { base: 'rgba(245, 158, 11, ', glow: 'rgba(217, 119, 6, 0.35)' },  // Warm amber
      { base: 'rgba(52, 211, 153, ', glow: 'rgba(16, 185, 129, 0.35)' }, // Emerald
      { base: 'rgba(110, 231, 183, ', glow: 'rgba(52, 211, 153, 0.3)' }, // Soft mint
      { base: 'rgba(253, 230, 138, ', glow: 'rgba(251, 191, 36, 0.45)' },// Pale yellow
    ];

    // Well-balanced particle count: rich enough to create ambient depth, clean enough not to clutter (~36-44 total)
    const particleCount = Math.min(Math.floor((window.innerWidth * window.innerHeight) / 38000) + 24, 42);
    const particles: Particle[] = [];

    for (let i = 0; i < particleCount; i++) {
      const isLargeBokeh = Math.random() < 0.22; // subtle soft bokeh motes
      const colorScheme = palette[Math.floor(Math.random() * palette.length)];
      // Refined radii: fine golden dust (0.8 - 1.6px) and soft glowing bokeh (2.4 - 4.2px)
      const radius = isLargeBokeh
        ? Math.random() * 1.8 + 2.4
        : Math.random() * 0.8 + 0.8;

      particles.push({
        x: Math.random() * width,
        y: Math.random() * height,
        baseVx: (Math.random() - 0.5) * 0.25,
        baseVy: -Math.random() * 0.32 - 0.1, // gentle atmospheric upward drift
        vx: 0,
        vy: 0,
        radius,
        baseRadius: radius,
        color: colorScheme.base,
        glowColor: colorScheme.glow,
        alpha: Math.random() * 0.4 + 0.15,
        targetAlpha: Math.random() * 0.5 + 0.22,
        pulseSpeed: Math.random() * 0.014 + 0.005,
        isHexBokeh: isLargeBokeh && Math.random() > 0.5,
        mass: radius * 1.6,
      });
    }

    // Dynamic spark particles generated by mouse interactions (minimal and subtle)
    const sparks: InteractiveSpark[] = [];

    const addSpark = (x: number, y: number, count = 1) => {
      for (let i = 0; i < count; i++) {
        if (sparks.length > 30) sparks.shift();
        const angle = Math.random() * Math.PI * 2;
        const speed = Math.random() * 1.4 + 0.3;
        const color = Math.random() > 0.4 ? 'rgba(251, 191, 36, ' : 'rgba(52, 211, 153, ';
        sparks.push({
          x: x + (Math.random() - 0.5) * 10,
          y: y + (Math.random() - 0.5) * 10,
          vx: Math.cos(angle) * speed,
          vy: Math.sin(angle) * speed - 0.2,
          radius: Math.random() * 0.8 + 0.5, // much smaller sparks
          alpha: 0.75,
          decay: Math.random() * 0.03 + 0.02,
          color,
        });
      }
    };

    // Event listeners for mouse and touch
    const onMouseMove = (e: MouseEvent) => {
      mouse.active = true;
      mouse.targetX = e.clientX;
      mouse.targetY = e.clientY;

      const dx = mouse.targetX - mouse.prevX;
      const dy = mouse.targetY - mouse.prevY;
      mouse.speed = Math.sqrt(dx * dx + dy * dy);
      mouse.prevX = mouse.targetX;
      mouse.prevY = mouse.targetY;

      // Spawn subtle golden sparks when the cursor glides across the hero
      if (mouse.speed > 8 && Math.random() < 0.35) {
        addSpark(mouse.targetX, mouse.targetY, 1);
      }
    };

    const onMouseLeave = () => {
      mouse.active = false;
      mouse.targetX = -1000;
      mouse.targetY = -1000;
    };

    const onClick = (e: MouseEvent) => {
      addSpark(e.clientX, e.clientY, 3);
    };

    const onTouchMove = (e: TouchEvent) => {
      if (e.touches.length > 0) {
        mouse.active = true;
        mouse.targetX = e.touches[0].clientX;
        mouse.targetY = e.touches[0].clientY;
        if (Math.random() < 0.4) {
          addSpark(mouse.targetX, mouse.targetY, 1);
        }
      }
    };

    const onTouchEnd = () => {
      mouse.active = false;
      mouse.targetX = -1000;
      mouse.targetY = -1000;
    };

    window.addEventListener('mousemove', onMouseMove, { passive: true });
    window.addEventListener('mouseleave', onMouseLeave, { passive: true });
    window.addEventListener('click', onClick, { passive: true });
    window.addEventListener('touchmove', onTouchMove, { passive: true });
    window.addEventListener('touchend', onTouchEnd, { passive: true });

    // Helper: Draw decorative hexagonal bokeh aperture
    const drawHexagon = (c: CanvasRenderingContext2D, x: number, y: number, r: number) => {
      c.beginPath();
      for (let i = 0; i < 6; i++) {
        const angle = (Math.PI / 3) * i;
        const hx = x + r * Math.cos(angle);
        const hy = y + r * Math.sin(angle);
        if (i === 0) c.moveTo(hx, hy);
        else c.lineTo(hx, hy);
      }
      c.closePath();
      c.fill();
    };

    // Main animation loop
    const render = () => {
      ctx.clearRect(0, 0, width, height);

      // Smooth mouse coordinate tracking
      if (mouse.targetX > -500) {
        mouse.x += (mouse.targetX - mouse.x) * 0.12;
        mouse.y += (mouse.targetY - mouse.y) * 0.12;
      } else {
        mouse.x = -1000;
        mouse.y = -1000;
      }

      // 1. Ambient Radial Cursor Halo
      if (mouse.active && mouse.x > 0 && mouse.y > 0) {
        const haloGrad = ctx.createRadialGradient(
          mouse.x,
          mouse.y,
          0,
          mouse.x,
          mouse.y,
          mouse.radius * 1.3
        );
        haloGrad.addColorStop(0, 'rgba(245, 158, 11, 0.04)');
        haloGrad.addColorStop(0.5, 'rgba(16, 185, 129, 0.02)');
        haloGrad.addColorStop(1, 'rgba(0, 0, 0, 0)');
        ctx.fillStyle = haloGrad;
        ctx.beginPath();
        ctx.arc(mouse.x, mouse.y, mouse.radius * 1.3, 0, Math.PI * 2);
        ctx.fill();
      }

      // 2. Process and Render Main Atmospheric Particles
      for (let i = 0; i < particles.length; i++) {
        const p = particles[i];

        // Interaction with mouse: repulsion + aerodynamic swirl
        if (mouse.x > -500 && mouse.y > -500) {
          const dx = p.x - mouse.x;
          const dy = p.y - mouse.y;
          const distSq = dx * dx + dy * dy;
          const maxDist = mouse.radius;

          if (distSq < maxDist * maxDist && distSq > 4) {
            const dist = Math.sqrt(distSq);
            const force = (1 - dist / maxDist) * 1.5; // gentle, subtle nudge
            const nx = dx / dist;
            const ny = dy / dist;

            // Push outward gently
            p.vx += (nx * force * 1.1) / p.mass;
            p.vy += (ny * force * 1.1) / p.mass;

            // Subtle rotational swirl around cursor
            p.vx += (-ny * force * 0.4) / p.mass;
            p.vy += (nx * force * 0.4) / p.mass;

            // Temporary luminous activation
            p.targetAlpha = Math.min(1, p.targetAlpha + 0.03);
          }
        }

        // Apply friction/damping to interactive velocity to return to natural drift
        p.vx *= 0.94;
        p.vy *= 0.94;

        // Update position: drift velocity + interactive displacement
        p.x += p.baseVx + p.vx;
        p.y += p.baseVy + p.vy;

        // Wrap around boundaries smoothly
        if (p.y < -30) {
          p.y = height + 30;
          p.x = Math.random() * width;
          p.vx = 0;
          p.vy = 0;
        } else if (p.y > height + 30) {
          p.y = -30;
          p.x = Math.random() * width;
        }

        if (p.x < -30) p.x = width + 30;
        if (p.x > width + 30) p.x = -30;

        // Breathing alpha oscillation
        p.alpha += (p.targetAlpha - p.alpha) * p.pulseSpeed;
        if (Math.abs(p.targetAlpha - p.alpha) < 0.04) {
          p.targetAlpha = Math.random() * 0.5 + 0.15;
        }

        ctx.fillStyle = `${p.color}${p.alpha})`;

        // Render Bokeh Hexagon or Soft Glow Point
        if (p.isHexBokeh) {
          drawHexagon(ctx, p.x, p.y, p.radius * 1.4);
        } else {
          ctx.beginPath();
          ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
          ctx.fill();

          // Subtle glow aura on larger motes
          if (p.radius > 2) {
            ctx.fillStyle = p.glowColor;
            ctx.beginPath();
            ctx.arc(p.x, p.y, p.radius * 1.8, 0, Math.PI * 2);
            ctx.fill();
          }
        }

        // 3. Connective genetic affinity lines between nearby particles close to mouse
        if (mouse.x > -500 && mouse.y > -500) {
          for (let j = i + 1; j < particles.length; j++) {
            const p2 = particles[j];
            const pDistSq = (p.x - p2.x) ** 2 + (p.y - p2.y) ** 2;
            if (pDistSq < 6000) {
              // Only draw if both are within mouse influence proximity
              const mouseDistToMidpoint = Math.hypot(
                (p.x + p2.x) / 2 - mouse.x,
                (p.y + p2.y) / 2 - mouse.y
              );
              if (mouseDistToMidpoint < mouse.radius * 1.1) {
                const lineAlpha = (1 - pDistSq / 6000) * 0.15 * (1 - mouseDistToMidpoint / (mouse.radius * 1.1));
                ctx.strokeStyle = `rgba(251, 191, 36, ${lineAlpha})`;
                ctx.lineWidth = 0.75;
                ctx.beginPath();
                ctx.moveTo(p.x, p.y);
                ctx.lineTo(p2.x, p2.y);
                ctx.stroke();
              }
            }
          }
        }
      }

      // 4. Render Dynamic Interactive Sparks
      for (let i = sparks.length - 1; i >= 0; i--) {
        const s = sparks[i];
        s.x += s.vx;
        s.y += s.vy;
        s.alpha -= s.decay;

        if (s.alpha <= 0) {
          sparks.splice(i, 1);
          continue;
        }

        ctx.fillStyle = `${s.color}${s.alpha})`;
        ctx.beginPath();
        ctx.arc(s.x, s.y, s.radius * s.alpha, 0, Math.PI * 2);
        ctx.fill();
      }

      animationFrameId = requestAnimationFrame(render);
    };

    render();

    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('mousemove', onMouseMove);
      window.removeEventListener('mouseleave', onMouseLeave);
      window.removeEventListener('click', onClick);
      window.removeEventListener('touchmove', onTouchMove);
      window.removeEventListener('touchend', onTouchEnd);
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  return (
    <canvas
      id="interactive-particle-canvas"
      ref={canvasRef}
      className="absolute inset-0 pointer-events-none z-10"
      aria-hidden="true"
    />
  );
}
